### PR TITLE
LRQA-67826 - Workflow Automated Test CanNotUpdateDueDateOfUnassignedTasks

### PR DESCRIPTION
**Pull request by alanafergs**
https://issues.liferay.com/browse/LRQA-67826

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:reopen

**Comment by lucasperj** [comment]
ci:reopen

**Comment by lucasperj** [comment]
ci:reopen

**Comment by alanafergs** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
Just started reviewing :)

**Comment by lucasperj** [comment]
Sent here : https://github.com/lucasperj/liferay-portal/pull/196

**Pull request closed without merging**
