### PR TITLE
LPS-159050 Uniform Automated test | Adding new Smoke tests for directly upgrade from 6.1 to 7.4

### PR DESCRIPTION
**Pull request by lucasperj**
JIRA Ticket:
[LPS-158183](https://issues.liferay.com/browse/LPS-158183)

Motivation:
Facilitate the upgrades from the customer and Support (quicker to fix issues) perspective.

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:relevant

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:upgrade

**Comment by CarlosBrichete** [comment]
Hey @lucasperj , just 2 things:

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
ci:reopen

**Pull request closed without merging**
