### PR TITLE
Workflow Automated Test - LRQA-71798 | master

### PR DESCRIPTION
**Pull request by sirfabios**

### CODE REVIEW

**Comment by sirfabios** [comment]
https://issues.liferay.com/browse/LRQA-70697

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
Just started reviewing :)

**Comment by lucasperj** [comment]
Sent here : [https://github.com/lucasperj/liferay-portal/pull/181](https://github.com/lucasperj/liferay-portal/pull/181)

**Pull request closed without merging**
