### PR TITLE
LPS-195812

### PR DESCRIPTION
**Pull request by lucasperj**

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
test ci:test:sf

**Comment by lucasperj** [comment]
ci:stop

**Comment by john-co** [comment]
Hi @lucasperj , can you add some more context in your first comment?

**Comment by john-co** [comment]
Could you help me out with some context and add a description of the issue and the proposed solution in the PR?

I like to reference this guideline to better streamline the PR review process: https://github.com/liferay/liferay-frontend-guidelines/blob/master/general/pull_requests.md#write-useful-descriptions-and-titles

**Comment by john-co** [comment]
Also, the ticket https://liferay.atlassian.net/browse/LPS-195812 doesn't seem to match what's going on in the PR.

**Comment by lucasperj** [comment]
test ci:test:sf

**Comment by lucasperj** [comment]
test ci:test:sf

**Comment by lucasperj** [comment]
test ci:test:sf

**Pull request closed without merging**
