### PR TITLE
Combined PR of KaleoFormsProcessListView testcases: LRQA-70662, LRQA-70663, LRQA-70664, LRQA-70665, LRQA-70666, LRQA-70667, LRQA-70668, LRQA-70669, LRQA-70670, LRQA-70671, LRQA-70672, LRQA-70673, LRQA-70674, LRQA-70675, LRQA-70676

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LRQA-70636 (tickets KaleoFormsProcessListView)

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Review by lucasperj — CHANGES_REQUESTED** [review]

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Review by lucasperj — APPROVED** [review]

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:forward

**Pull request closed without merging**
