### PR TITLE
Workflow Automated Test - LRQA-70711 | master

### PR DESCRIPTION
**Pull request by Italo-gabriel**
https://issues.liferay.com/browse/LRQA-70711

### CODE REVIEW

**Comment by Italo-gabriel** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
Just started reviewing :)

**Comment by lucasperj** [comment]
Combined and sent [here](https://github.com/lucasperj/liferay-portal/pull/169).

**Pull request closed without merging**
