### PR TITLE
LPS-186413

### PR DESCRIPTION
**Pull request by lucasperj**

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Hey @lucasperj, any update on this? we need to commit this fix for LXC.

Thanks

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
ci:test:upgrade

**Pull request closed without merging**
