### PR TITLE
Combined PR of ResourcesListView testcase: LRQA-71920, LRQA-71921, LRQA-71922, LRQA-71923, LRQA-71924, LRQA-71925, LRQA-71926

### PR DESCRIPTION
**Pull request by alanafergs**
https://issues.liferay.com/browse/LRQA-71920
https://issues.liferay.com/browse/LRQA-71921
https://issues.liferay.com/browse/LRQA-71922
https://issues.liferay.com/browse/LRQA-71923
https://issues.liferay.com/browse/LRQA-71924
https://issues.liferay.com/browse/LRQA-71925
https://issues.liferay.com/browse/LRQA-71926

### CODE REVIEW

**Comment by alanafergs** [comment]
ci:test:sf

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by alanafergs** [comment]
ci:test:sf

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Pull request closed without merging**
